# Generated by Django 3.2.7 on 2021-09-10 10:52

import django.core.validators
from django.db import migrations, models
import vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20210910_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
