# Generated by Django 3.2.7 on 2022-01-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_auto_20220126_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(),
        ),
    ]
