# Generated by Django 3.2.7 on 2022-01-30 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_auto_20220130_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='min_experience',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
